#!/bin/bash
# Batch parse all 50 chapters of Genesis
# Generated by Claude Code

set -e  # Exit on error

echo "Starting batch parse of Genesis (all 50 chapters)..."
echo "Start time: $(date)"

# Genesis verse counts per chapter
declare -A VERSE_COUNTS=(
    [1]=31 [2]=25 [3]=24 [4]=26 [5]=32 [6]=22 [7]=24 [8]=22 [9]=29 [10]=32
    [11]=32 [12]=20 [13]=18 [14]=24 [15]=21 [16]=16 [17]=27 [18]=33 [19]=38
    [20]=18 [21]=34 [22]=24 [23]=20 [24]=67 [25]=34 [26]=35 [27]=46 [28]=22
    [29]=35 [30]=43 [31]=55 [32]=32 [33]=20 [34]=31 [35]=29 [36]=43 [37]=36
    [38]=30 [39]=23 [40]=23 [41]=57 [42]=38 [43]=34 [44]=34 [45]=28 [46]=34
    [47]=31 [48]=22 [49]=33 [50]=26
)

total_verses=0
successful=0
uncertain=0

# Parse each chapter
for chapter in {1..50}; do
    verse_count=${VERSE_COUNTS[$chapter]}
    echo ""
    echo "=== Parsing Genesis Chapter $chapter (${verse_count} verses) ==="

    for verse in $(seq 1 $verse_count); do
        echo -n "  Gen ${chapter}:${verse} ... "

        if python run_parser_temp.py $chapter $verse > /dev/null 2>&1; then
            # Check if output file was created
            if [ -f "output/Gen/$chapter/${verse}" ]; then
                echo "✓"
                ((successful++))
            elif [ -f "output/Gen/$chapter/${verse}_uncertain" ]; then
                echo "⚠ uncertain"
                ((uncertain++))
            else
                echo "✗ failed"
            fi
        else
            echo "✗ error"
        fi

        ((total_verses++))
    done

    echo "  Completed chapter $chapter: $successful successful, $uncertain uncertain"
done

echo ""
echo "=== Batch Parse Complete ==="
echo "End time: $(date)"
echo "Total verses processed: $total_verses"
echo "Successful: $successful"
echo "Uncertain: $uncertain"
echo ""
echo "Output saved to: output/Gen/{1..50}/"
echo "Check issue logs in output/ directory"
